# Generated by Django 3.2.5 on 2021-07-24 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_no', models.TextField(unique=True)),
                ('name', models.TextField()),
                ('email', models.TextField()),
                ('mobile_no', models.TextField(null=True)),
            ],
        ),
    ]
